### Arrays NumPy

In [1]:
myList = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(myList)

In [4]:
arr

array([1, 2, 3])

In [7]:
myMath = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(myMath)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.81602306, 0.59161586, 0.66748638, 0.53779203, 0.69271849])

In [22]:
np.random.rand(5,5)

array([[0.62322274, 0.86850424, 0.09450583, 0.72451184, 0.70733468],
       [0.76104539, 0.10639815, 0.95981922, 0.64569586, 0.02277161],
       [0.78014395, 0.17081287, 0.38263393, 0.89132765, 0.32693209],
       [0.79356024, 0.83121561, 0.42997215, 0.34294904, 0.66470256],
       [0.34999722, 0.35724135, 0.24377968, 0.56651546, 0.02589403]])

In [23]:
np.random.randn(4,4)

array([[-0.80373945, -0.81849646, -0.56318775,  0.9005225 ],
       [ 1.23838225, -0.84906662, -0.70408628, -1.43522851],
       [ 0.55686998, -2.10818003, -0.68958145, -1.57451877],
       [-0.16816692, -0.02124866,  1.29167597,  0.83801824]])

In [25]:
np.random.randint(1,100,10)

array([44, 38, 92, 26, 34, 12, 79, 18, 72, 87])

In [26]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr = np.random.randint(0,50,10)

In [30]:
ranarr

array([20, 33, 47, 35, 48, 37, 33,  7, 11,  4])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
ranarr.max()

48

In [36]:
ranarr.min()

4

In [37]:
ranarr

array([20, 33, 47, 35, 48, 37, 33,  7, 11,  4])

In [38]:
ranarr.argmax()

4

In [39]:
ranarr.argmin()

9

In [42]:
arr = arr.reshape(5,5)

In [44]:
arr.shape

(5, 5)

In [45]:
arr.dtype

dtype('int32')

In [46]:
from numpy.random import randint

In [47]:
randint(2,10)

8