### Arrays NumPy

In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
sliceOfArr = arr[0:6]

In [14]:
sliceOfArr

array([100, 100, 100, 100, 100,   5])

In [16]:
sliceOfArr[:] = 99

In [17]:
sliceOfArr

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arrCopy = arr.copy()

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arrCopy[:] = 25

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
arr2D = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [29]:
arr2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr2D[1][2]

30

In [35]:
arr2D[:2,1:]

array([[10, 15],
       [25, 30]])

In [36]:
arr = np.arange(0,11)

In [38]:
boolArr = arr > 5

In [39]:
boolArr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [40]:
arr[boolArr]

array([ 6,  7,  8,  9, 10])

In [41]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [42]:
arr2D = np.arange(50).reshape(5,10)

In [43]:
arr2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [44]:
arr2D[1:3,3:5]

array([[13, 14],
       [23, 24]])