### Arrays NumPy

In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
sliceOfArr = arr[0:6]

In [14]:
sliceOfArr

array([100, 100, 100, 100, 100,   5])

In [16]:
sliceOfArr[:] = 99

In [17]:
sliceOfArr

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arrCopy = arr.copy()

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arrCopy[:] = 25

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
arr2D = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [29]:
arr2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr2D[1][2]

30

In [35]:
arr2D[:2,1:]

array([[10, 15],
       [25, 30]])

In [36]:
arr = np.arange(0,11)

In [38]:
boolArr = arr > 5

In [39]:
boolArr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [40]:
arr[boolArr]

array([ 6,  7,  8,  9, 10])

In [41]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [42]:
arr2D = np.arange(50).reshape(5,10)

In [43]:
arr2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [44]:
arr2D[1:3,3:5]

array([[13, 14],
       [23, 24]])

## Operations

In [60]:
arr = np.arange(0,11)

In [61]:
arr = arr + arr

In [62]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [63]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
arr * arr

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324, 400])

In [65]:
arr + 100

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120])

In [66]:
arr - 100

array([-100,  -98,  -96,  -94,  -92,  -90,  -88,  -86,  -84,  -82,  -80])

In [68]:
#arr / arr

In [69]:
arr ** 2

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324, 400], dtype=int32)

In [70]:
np.sqrt(arr)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595])

In [71]:
np.exp(arr)

array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
       2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06,
       8.88611052e+06, 6.56599691e+07, 4.85165195e+08])

In [72]:
np.max(arr)

20

In [73]:
arr.max()

20

In [74]:
np.sin(arr)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725,
        0.91294525])